### ISSUE TITLE
The InterUSS DataNode occasionally returns a 500 HTTP status code.

### ISSUE THREAD

**Issue by vbaskara** [wing-aviation/InterUSS-Platform#19] opened 2018-09-13 00:28 UTC
2018-09-12 15:36:05 [pool-0] INFO gov.nasa.utm.ussn.ussapiservice.ConcurrencySender:93 Making a rest call http://35.193.160.127:8121/GridCellOperator/9/73/191 GET <{Content-Type=[application/json]}>
2018-09-12 15:36:05 [pool-0] ERROR gov.nasa.utm.ussn.ussapiservice.ConcurrencySender:100 
HttpStatusCodeException code:500 body:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

}

**Comment by BenjaminPelletier** [comment] 2018-09-13 23:45
This particular 500 was being caused by an ImmatureSignatureError in JWT while validating the access token.  It was corrected on the tcl4 branch in commit 3fff76100a33e0cd1a83bd3b6aaac18b4f9e1483

**Comment by hi-kevin** [comment] 2018-11-11 06:08
Closing, as it has been corrected, and issue #20 will address refactoring all error handling.

**Closed by hi-kevin** 2018-11-11 06:08 UTC
